galaxy_info:
  role_name: #role name
  author: # Your name
  description: 'Your Discription'

  issue_tracker_url: https://github.com/ComplianceAsCode/content/issues

  license: BSD-3-Clause

  min_ansible_version: 2.5

  platforms:
  - name: EL
    versions:
    - 8

  galaxy_tags:
  - system
  - hardening
  - openscap
  - ssg
  - scap
  - security
  - compliance
  - complianceascode
  - disa
  - stig
  - redhatofficial
  - redhat

dependencies: []
